// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bag.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Messages
  public sealed class C_To_S_Get_BagData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_Get_BagData_Msg> _parser = new pb::MessageParser<C_To_S_Get_BagData_Msg>(() => new C_To_S_Get_BagData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_Get_BagData_Msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed class S_To_C_Get_BagData_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_Get_BagData_Msg> _parser = new pb::MessageParser<S_To_C_Get_BagData_Msg>(() => new S_To_C_Get_BagData_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_Get_BagData_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "Itemid" field.</summary>
    public const int ItemidFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_itemid_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> itemid_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Itemid {
      get { return itemid_; }
    }

    /// <summary>Field number for the "BagCount" field.</summary>
    public const int BagCountFieldNumber = 2;
    private int bagCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BagCount {
      get { return bagCount_; }
      set {
        bagCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      itemid_.WriteTo(output, _repeated_itemid_codec);
      if (BagCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BagCount);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += itemid_.CalculateSize(_repeated_itemid_codec);
      if (BagCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BagCount);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            itemid_.AddEntriesFrom(input, _repeated_itemid_codec);
            break;
          }
          case 16: {
            BagCount = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
