// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Role.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Enums
  public enum jobType {
    Zhanshi = 0,
    Fashi = 1,
    Daoshi = 2,
  }

  public enum CreateRoleResult {
    CreateRoleSuss = 0,
    NoName = 1,
    Weihu = 2,
  }

  public enum Role_EnterGame_Result {
    EnterGame = 0,
    NoRole = 1,
  }

  #endregion

  #region Messages
  public sealed class C_2_S_CreateRole_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_CreateRole_Msg> _parser = new pb::MessageParser<C_2_S_CreateRole_Msg>(() => new C_2_S_CreateRole_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_CreateRole_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "jobType" field.</summary>
    public const int JobTypeFieldNumber = 1;
    private global::MyGame.jobType jobType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.jobType JobType {
      get { return jobType_; }
      set {
        jobType_ = value;
      }
    }

    /// <summary>Field number for the "jobName" field.</summary>
    public const int JobNameFieldNumber = 2;
    private string jobName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string JobName {
      get { return jobName_; }
      set {
        jobName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (JobType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) JobType);
      }
      if (JobName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(JobName);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (JobType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) JobType);
      }
      if (JobName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JobName);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            jobType_ = (global::MyGame.jobType) input.ReadEnum();
            break;
          }
          case 18: {
            JobName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed class S_2_C_CreateRole_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_CreateRole_Msg> _parser = new pb::MessageParser<S_2_C_CreateRole_Msg>(() => new S_2_C_CreateRole_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_CreateRole_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "CreateRoleResult" field.</summary>
    public const int CreateRoleResultFieldNumber = 1;
    private global::MyGame.CreateRoleResult createRoleResult_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.CreateRoleResult CreateRoleResult {
      get { return createRoleResult_; }
      set {
        createRoleResult_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CreateRoleResult != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) CreateRoleResult);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CreateRoleResult != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CreateRoleResult);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            createRoleResult_ = (global::MyGame.CreateRoleResult) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed class C_2_S_Role_EnterGame_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_Role_EnterGame_Msg> _parser = new pb::MessageParser<C_2_S_Role_EnterGame_Msg>(() => new C_2_S_Role_EnterGame_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_Role_EnterGame_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "roleGUID" field.</summary>
    public const int RoleGUIDFieldNumber = 1;
    private int roleGUID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RoleGUID {
      get { return roleGUID_; }
      set {
        roleGUID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RoleGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoleGUID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RoleGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoleGUID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            RoleGUID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class S_2_C_Role_EnterGame_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_Role_EnterGame_Msg> _parser = new pb::MessageParser<S_2_C_Role_EnterGame_Msg>(() => new S_2_C_Role_EnterGame_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_Role_EnterGame_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "Role_EnterGame_Result" field.</summary>
    public const int RoleEnterGameResultFieldNumber = 1;
    private global::MyGame.Role_EnterGame_Result roleEnterGameResult_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.Role_EnterGame_Result RoleEnterGameResult {
      get { return roleEnterGameResult_; }
      set {
        roleEnterGameResult_ = value;
      }
    }

    /// <summary>Field number for the "roleGUID" field.</summary>
    public const int RoleGUIDFieldNumber = 2;
    private int roleGUID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RoleGUID {
      get { return roleGUID_; }
      set {
        roleGUID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RoleEnterGameResult != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RoleEnterGameResult);
      }
      if (RoleGUID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RoleGUID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RoleEnterGameResult != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RoleEnterGameResult);
      }
      if (RoleGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoleGUID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            roleEnterGameResult_ = (global::MyGame.Role_EnterGame_Result) input.ReadEnum();
            break;
          }
          case 16: {
            RoleGUID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
