// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shop.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Enums
  /// <summary>
  ///商品类型
  /// </summary>
  public enum GoodsType {
    Equip = 0,
    Medicine = 1,
    Box = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///获取商品信息列表
  /// </summary>
  public sealed class S_2_C_GoodsList_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_GoodsList_Msg> _parser = new pb::MessageParser<S_2_C_GoodsList_Msg>(() => new S_2_C_GoodsList_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_GoodsList_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "goodsList" field.</summary>
    public const int GoodsListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MyGame.GoodsInfos> _repeated_goodsList_codec
        = pb::FieldCodec.ForMessage(10, global::MyGame.GoodsInfos.Parser);
    private pbc::RepeatedField<global::MyGame.GoodsInfos> goodsList_ = new pbc::RepeatedField<global::MyGame.GoodsInfos>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.GoodsInfos> GoodsList {
      get { return goodsList_; }
      set{goodsList_ = value;}
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      goodsList_.WriteTo(output, _repeated_goodsList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += goodsList_.CalculateSize(_repeated_goodsList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            goodsList_.AddEntriesFrom(input, _repeated_goodsList_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class C_2_S_Buy_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_Buy_Msg> _parser = new pb::MessageParser<C_2_S_Buy_Msg>(() => new C_2_S_Buy_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_Buy_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 1;
    private global::MyGame.GoodsInfos infos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.GoodsInfos Infos {
      get { return infos_; }
      set {
        infos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (infos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Infos);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (infos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Infos);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (infos_ == null) {
              infos_ = new global::MyGame.GoodsInfos();
            }
            input.ReadMessage(infos_);
            break;
          }
        }
      }
    }

  }

  public sealed class S_2_C_Buy_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_Buy_Msg> _parser = new pb::MessageParser<S_2_C_Buy_Msg>(() => new S_2_C_Buy_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_Buy_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 1;
    private global::MyGame.GoodsInfos infos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.GoodsInfos Infos {
      get { return infos_; }
      set {
        infos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (infos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Infos);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (infos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Infos);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (infos_ == null) {
              infos_ = new global::MyGame.GoodsInfos();
            }
            input.ReadMessage(infos_);
            break;
          }
        }
      }
    }

  }

  public sealed class C_2_S_Delet_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_Delet_Msg> _parser = new pb::MessageParser<C_2_S_Delet_Msg>(() => new C_2_S_Delet_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_Delet_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 1;
    private global::MyGame.GoodsInfos infos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.GoodsInfos Infos {
      get { return infos_; }
      set {
        infos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (infos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Infos);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (infos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Infos);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (infos_ == null) {
              infos_ = new global::MyGame.GoodsInfos();
            }
            input.ReadMessage(infos_);
            break;
          }
        }
      }
    }

  }

  public sealed class S_2_C_Delet_Msg : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_Delet_Msg> _parser = new pb::MessageParser<S_2_C_Delet_Msg>(() => new S_2_C_Delet_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_Delet_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 1;
    private global::MyGame.GoodsInfos infos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.GoodsInfos Infos {
      get { return infos_; }
      set {
        infos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (infos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Infos);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (infos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Infos);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (infos_ == null) {
              infos_ = new global::MyGame.GoodsInfos();
            }
            input.ReadMessage(infos_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///商品信息
  /// </summary>
  public sealed class GoodsInfos : pb::IMessage {
    private static readonly pb::MessageParser<GoodsInfos> _parser = new pb::MessageParser<GoodsInfos>(() => new GoodsInfos());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GoodsInfos> Parser { get { return _parser; } }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 3;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sale" field.</summary>
    public const int SaleFieldNumber = 4;
    private int sale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Sale {
      get { return sale_; }
      set {
        sale_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 5;
    private global::MyGame.GoodsType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.GoodsType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Icon);
      }
      if (Sale != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Sale);
      }
      if (Type != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (Sale != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sale);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Icon = input.ReadString();
            break;
          }
          case 32: {
            Sale = input.ReadInt32();
            break;
          }
          case 40: {
            type_ = (global::MyGame.GoodsType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
