// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoleList.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Messages
  public sealed class S_To_C_RoleList : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_RoleList> _parser = new pb::MessageParser<S_To_C_RoleList>(() => new S_To_C_RoleList());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_RoleList> Parser { get { return _parser; } }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MyGame.XuanRoleData> _repeated_data_codec
        = pb::FieldCodec.ForMessage(10, global::MyGame.XuanRoleData.Parser);
    private readonly pbc::RepeatedField<global::MyGame.XuanRoleData> data_ = new pbc::RepeatedField<global::MyGame.XuanRoleData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.XuanRoleData> Data {
      get { return data_; }
    }

    /// <summary>Field number for the "Money" field.</summary>
    public const int MoneyFieldNumber = 2;
    private float money_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Money {
      get { return money_; }
      set {
        money_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      data_.WriteTo(output, _repeated_data_codec);
      if (Money != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Money);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_repeated_data_codec);
      if (Money != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
          case 21: {
            Money = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed class XuanRoleData : pb::IMessage {
    private static readonly pb::MessageParser<XuanRoleData> _parser = new pb::MessageParser<XuanRoleData>(() => new XuanRoleData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<XuanRoleData> Parser { get { return _parser; } }

    /// <summary>Field number for the "RoleName" field.</summary>
    public const int RoleNameFieldNumber = 1;
    private string roleName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RoleName {
      get { return roleName_; }
      set {
        roleName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Path" field.</summary>
    public const int PathFieldNumber = 2;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Roleid" field.</summary>
    public const int RoleidFieldNumber = 3;
    private string roleid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Roleid {
      get { return roleid_; }
      set {
        roleid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RoleName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoleName);
      }
      if (Path.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Path);
      }
      if (Roleid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Roleid);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RoleName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoleName);
      }
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (Roleid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Roleid);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            RoleName = input.ReadString();
            break;
          }
          case 18: {
            Path = input.ReadString();
            break;
          }
          case 26: {
            Roleid = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
