// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Text.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace MyGame {

  #region Enums
  /// <summary>
  ///聊天结果枚举
  /// </summary>
  public enum Chat_Result {
    Succ = 0,
    Level = 1,
    Mgc = 2,
    TargetNoLine = 3,
    TatgetIh = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  ///聊天C_2_S--世界聊天请求
  /// </summary>
  public sealed class C_To_S_WorldChat_Msg : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_WorldChat_Msg> _parser = new pb::MessageParser<C_To_S_WorldChat_Msg>(() => new C_To_S_WorldChat_Msg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_WorldChat_Msg> Parser { get { return _parser; } }

    /// <summary>Field number for the "textDesc" field.</summary>
    public const int TextDescFieldNumber = 1;
    private string textDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TextDesc {
      get { return textDesc_; }
      set {
        textDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chatDataList" field.</summary>
    public const int ChatDataListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::MyGame.ChatData> _repeated_chatDataList_codec
        = pb::FieldCodec.ForMessage(18, global::MyGame.ChatData.Parser);
    private readonly pbc::RepeatedField<global::MyGame.ChatData> chatDataList_ = new pbc::RepeatedField<global::MyGame.ChatData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MyGame.ChatData> ChatDataList {
      get { return chatDataList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TextDesc.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TextDesc);
      }
      chatDataList_.WriteTo(output, _repeated_chatDataList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TextDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextDesc);
      }
      size += chatDataList_.CalculateSize(_repeated_chatDataList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            TextDesc = input.ReadString();
            break;
          }
          case 18: {
            chatDataList_.AddEntriesFrom(input, _repeated_chatDataList_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class ChatData : pb::IMessage {
    private static readonly pb::MessageParser<ChatData> _parser = new pb::MessageParser<ChatData>(() => new ChatData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChatData> Parser { get { return _parser; } }

    /// <summary>Field number for the "textDesc" field.</summary>
    public const int TextDescFieldNumber = 1;
    private string textDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TextDesc {
      get { return textDesc_; }
      set {
        textDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "speak" field.</summary>
    public const int SpeakFieldNumber = 2;
    private string speak_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Speak {
      get { return speak_; }
      set {
        speak_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "toSpeak" field.</summary>
    public const int ToSpeakFieldNumber = 3;
    private string toSpeak_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ToSpeak {
      get { return toSpeak_; }
      set {
        toSpeak_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TextDesc.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TextDesc);
      }
      if (Speak.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Speak);
      }
      if (ToSpeak.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ToSpeak);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TextDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextDesc);
      }
      if (Speak.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Speak);
      }
      if (ToSpeak.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ToSpeak);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            TextDesc = input.ReadString();
            break;
          }
          case 18: {
            Speak = input.ReadString();
            break;
          }
          case 26: {
            ToSpeak = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///聊天S_2_C--世界聊天结果回馈
  /// </summary>
  public sealed class S_To_C_WorldChat_Msgl : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_WorldChat_Msgl> _parser = new pb::MessageParser<S_To_C_WorldChat_Msgl>(() => new S_To_C_WorldChat_Msgl());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_WorldChat_Msgl> Parser { get { return _parser; } }

    /// <summary>Field number for the "r" field.</summary>
    public const int RFieldNumber = 1;
    private global::MyGame.Chat_Result r_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MyGame.Chat_Result R {
      get { return r_; }
      set {
        r_ = value;
      }
    }

    /// <summary>Field number for the "speak" field.</summary>
    public const int SpeakFieldNumber = 2;
    private string speak_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Speak {
      get { return speak_; }
      set {
        speak_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "textDesc" field.</summary>
    public const int TextDescFieldNumber = 3;
    private string textDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TextDesc {
      get { return textDesc_; }
      set {
        textDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) R);
      }
      if (Speak.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Speak);
      }
      if (TextDesc.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TextDesc);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (R != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) R);
      }
      if (Speak.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Speak);
      }
      if (TextDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextDesc);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            r_ = (global::MyGame.Chat_Result) input.ReadEnum();
            break;
          }
          case 18: {
            Speak = input.ReadString();
            break;
          }
          case 26: {
            TextDesc = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
